Fix (#780) jax_to_numpy did not handle NamedTuples
They caused "missing N required positional argument: 'name', ..." in _iterable_numpy_to_jax or _iterable_jax_to_numpy
as the for loop resulted in a generator that NamedTuples could not handle.

NamedTuple is not a useful base class, every used named type needs to be registered individually.
jax_to_numpy.register_namedtuple(NewNamedTuple)

[Bug Report] TypeError: <NamedTuple>.__new__() missing 1 required positional argument: '<argument>'