Fix (#780) jax_to_numpy did not handle NamedTuples
They caused "missing N required positional argument: 'name', ..." in _iterable_numpy_to_jax or _iterable_jax_to_numpy
as the for loop resulted in a generator that NamedTuples could not handle.

[Bug Report] TypeError: <NamedTuple>.__new__() missing 1 required positional argument: '<argument>'